// <auto-generated />
namespace Covid19CharitySystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v21));
        
        string IMigrationMetadata.Id
        {
            get { return "202008090810278_v2.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
